server:
  port: 9006

database:
  driver: mysql
  dsn: "root:root123@tcp(localhost:3306)/payment_db?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime: 3600
  log_mode: true
